import Foundation

/// Errors thrown when a file's `// viewlens:generated:begin/end` markers can't be trusted
/// enough to safely merge — every case means "abort and report", never "fall back to
/// overwriting the whole file" (MCP-17.12).
public enum MarkerParseError: Error, Equatable {
    case missingEndMarker(id: NonvisualID)
    case duplicateBeginMarker(id: NonvisualID)
    case malformedMarkerLine(String)
    case unmatchedEndMarker(id: NonvisualID)
}

/// Merges ViewLens-generated content into a marker-delimited region of a file, leaving
/// everything else — hand-written code before, after, or in other regions — byte-for-byte
/// untouched (MCP-17.12).
///
/// This is the safety mechanism that lets ``RegressionTestGenerator`` (MCP-17.11) write real
/// files to disk without risking a human's edits: a region is only ever replaced between its
/// own paired markers, and any anomaly (missing/duplicate/mismatched/malformed markers) throws
/// rather than silently overwriting the file.
public enum GeneratedRegionMerger {
    static let beginPrefix = "// viewlens:generated:begin "
    static let endPrefix = "// viewlens:generated:end "
    static let autoGeneratedWarning = "// AUTO-GENERATED by ViewLens \u{2014} edits inside this block are overwritten on regeneration. Edit outside the markers instead."

    /// Merges `newContent` for `regionID` into `existingFileContents`.
    ///
    /// - If `existingFileContents` is `nil`, or has no markers for `regionID`, the region is
    ///   appended at end-of-file wrapped in fresh markers (first-time generation).
    /// - If markers for `regionID` already exist, only the text strictly between them is
    ///   replaced; all other content — including other regions' markers and hand-written code
    ///   — is preserved exactly.
    /// - Throws ``MarkerParseError`` rather than guessing when `regionID`'s markers are
    ///   malformed, duplicated, or mismatched anywhere in `existingFileContents`.
    public static func merge(
        regionID: NonvisualID,
        newContent: String,
        into existingFileContents: String?
    ) throws -> String {
        let beginMarker = beginPrefix + regionID.rawValue
        let endMarker = endPrefix + regionID.rawValue
        let wrappedRegion = "\(beginMarker)\n\(autoGeneratedWarning)\n\(newContent)\n\(endMarker)"

        guard let existing = existingFileContents, !existing.isEmpty else {
            return wrappedRegion
        }

        let lines = existing.components(separatedBy: "\n")
        try validateMarkerPairing(lines: lines, regionID: regionID)

        guard let beginIndex = lines.firstIndex(where: { $0 == beginMarker }) else {
            // No existing region for this ID: append, preserving existing trailing content.
            let separator = existing.hasSuffix("\n") ? "" : "\n"
            return existing + separator + wrappedRegion + "\n"
        }
        // validateMarkerPairing guarantees a matching end marker exists after beginIndex.
        let endIndex = lines[(beginIndex + 1)...].firstIndex(where: { $0 == endMarker })!

        var merged = lines
        merged.replaceSubrange(beginIndex...endIndex, with: wrappedRegion.components(separatedBy: "\n"))
        return merged.joined(separator: "\n")
    }

    /// Validates that every begin/end marker pair for `regionID` (and only `regionID`) found
    /// in `lines` is well-formed: at most one begin, at most one end, and if either is
    /// present the other must be too, in the correct order.
    private static func validateMarkerPairing(lines: [String], regionID: NonvisualID) throws {
        let beginMarker = beginPrefix + regionID.rawValue
        let endMarker = endPrefix + regionID.rawValue
        // Broader than beginPrefix/endPrefix (which include the trailing space before the ID)
        // so a truncated marker missing its ID — e.g. from a bad hand-edit — is still
        // recognized as a marker attempt and rejected, rather than silently read as plain text.
        let markerLineSignature = "viewlens:generated:"

        for line in lines where line.contains(markerLineSignature) {
            let isWellFormedBegin = line.hasPrefix(beginPrefix) && line.count > beginPrefix.count
            let isWellFormedEnd = line.hasPrefix(endPrefix) && line.count > endPrefix.count
            guard isWellFormedBegin || isWellFormedEnd else {
                throw MarkerParseError.malformedMarkerLine(line)
            }
        }

        let beginIndices = lines.indices.filter { lines[$0] == beginMarker }
        let endIndices = lines.indices.filter { lines[$0] == endMarker }

        guard beginIndices.count <= 1 else {
            throw MarkerParseError.duplicateBeginMarker(id: regionID)
        }
        // Multiple end markers for one region are just as ambiguous as an end marker with
        // no matching begin — which one closes the region? Treat both as "unmatched".
        guard endIndices.count <= 1 else {
            throw MarkerParseError.unmatchedEndMarker(id: regionID)
        }

        switch (beginIndices.first, endIndices.first) {
        case (nil, nil):
            return
        case (.some, nil):
            throw MarkerParseError.missingEndMarker(id: regionID)
        case (nil, .some):
            throw MarkerParseError.unmatchedEndMarker(id: regionID)
        case (.some(let begin), .some(let end)):
            guard begin < end else {
                throw MarkerParseError.unmatchedEndMarker(id: regionID)
            }
        }
    }
}
