import Foundation

/// Structured metadata describing an isolated preview harness generated from a project context report.
public struct PreviewHarnessDescriptor: Codable, Sendable, Equatable {
    public let rootSymbol: String
    public let harnessSourceName: String
    public let harnessSource: String
    public let synthesizedMocks: [String]
    public let injectedEnvironmentObjects: [String]
    public let syntheticAssets: [SyntheticResourceDescriptor]
    public let baselineEligible: Bool
    public let scenario: String?

    public init(
        rootSymbol: String,
        harnessSourceName: String,
        harnessSource: String,
        synthesizedMocks: [String],
        injectedEnvironmentObjects: [String],
        syntheticAssets: [SyntheticResourceDescriptor],
        baselineEligible: Bool,
        scenario: String? = nil
    ) {
        self.rootSymbol = rootSymbol
        self.harnessSourceName = harnessSourceName
        self.harnessSource = harnessSource
        self.synthesizedMocks = synthesizedMocks
        self.injectedEnvironmentObjects = injectedEnvironmentObjects
        self.syntheticAssets = syntheticAssets
        self.baselineEligible = baselineEligible
        self.scenario = scenario
    }
}

/// Generates compilable, isolated SwiftUI preview harnesses from a resolved `ProjectContextReport`.
/// All generated harnesses and mocks are deterministic, sandboxed, and marked baseline-ineligible
/// whenever synthetic substitutions are used.
public enum PreviewHarnessGenerator {
    /// Generates a standalone `PreviewHarnessDescriptor` containing Swift code and metadata.
    public static func generateHarness(for report: ProjectContextReport) -> PreviewHarnessDescriptor {
        let rootSymbol = report.manifest.rootSymbol ?? (report.sourceClosure.first(where: { $0.isRoot })?.declaredSymbols.first ?? "RootView")
        let scenario = report.manifest.scenario
        let harnessName = "\(rootSymbol)_ViewLensPreviewHarness"

        var synthesizedMocks: [String] = []
        var injectedEnvironmentObjects: [String] = []

        var mockDeclarations: [String] = []
        var propertyDeclarations: [String] = []
        var viewModifiers: [String] = []

        // 1. Synthesize mocks for scenario requirements
        for req in report.scenarioRequirements {
            let mockClassName = "Mock\(req.typeName)"
            if !synthesizedMocks.contains(mockClassName) {
                synthesizedMocks.append(mockClassName)
                injectedEnvironmentObjects.append(req.typeName)

                mockDeclarations.append("""
final class \(mockClassName): ObservableObject {
    init() {}
}
""")
                let varName = "mock\(req.typeName)"
                propertyDeclarations.append("    @StateObject private var \(varName) = \(mockClassName)()")
                viewModifiers.append("            .environmentObject(\(varName))")
            }
        }

        // 2. Determine baseline eligibility (ineligible if any synthetic resources or mocks are active)
        let hasSyntheticResources = !report.syntheticResources.isEmpty
        let hasMocks = !synthesizedMocks.isEmpty
        let isBaselineEligible = !hasSyntheticResources && !hasMocks && report.status == .readyForBuild

        // 3. Assemble Swift source
        var lines: [String] = []
        lines.append("//")
        lines.append("// \(harnessName).swift")
        lines.append("// Generated by ViewLens Context Preview Harness Engine (MCP-19.6)")
        lines.append("//")
        lines.append("// Baseline eligible: \(isBaselineEligible ? "true" : "false (synthetic substitutions present)")")
        lines.append("//")
        lines.append("")
        lines.append("import SwiftUI")

        // Include any required modules
        for mod in report.modules where mod != "SwiftUI" && mod != "Foundation" {
            lines.append("import \(mod)")
        }

        lines.append("")
        if !mockDeclarations.isEmpty {
            lines.append("// MARK: - Synthetic Environment Mocks")
            lines.append(mockDeclarations.joined(separator: "\n\n"))
            lines.append("")
        }

        if !report.syntheticResources.isEmpty {
            lines.append("// MARK: - Synthetic Asset Placeholders (Baseline-Ineligible)")
            lines.append("struct ViewLensSyntheticAssetPlaceholder: View {")
            lines.append("    let name: String")
            lines.append("    var body: some View {")
            lines.append("        Rectangle()")
            lines.append("            .fill(Color.purple.opacity(0.15))")
            lines.append("            .overlay(Text(name).font(.caption2).foregroundColor(.purple))")
            lines.append("    }")
            lines.append("}")
            lines.append("")
        }

        lines.append("// MARK: - Generated Preview Harness Container")
        lines.append("struct \(harnessName): View {")
        if !propertyDeclarations.isEmpty {
            lines.append(propertyDeclarations.joined(separator: "\n"))
        }
        lines.append("    var body: some View {")
        lines.append("        \(rootSymbol)()")
        if !viewModifiers.isEmpty {
            lines.append(viewModifiers.joined(separator: "\n"))
        }
        lines.append("    }")
        lines.append("}")
        lines.append("")
        lines.append("#Preview(\"\(rootSymbol)\(scenario != nil ? " [\(scenario!)]" : "")\") {")
        lines.append("    \(harnessName)()")
        lines.append("}")
        lines.append("")

        let harnessSource = lines.joined(separator: "\n")

        return PreviewHarnessDescriptor(
            rootSymbol: rootSymbol,
            harnessSourceName: "\(harnessName).swift",
            harnessSource: harnessSource,
            synthesizedMocks: synthesizedMocks,
            injectedEnvironmentObjects: injectedEnvironmentObjects,
            syntheticAssets: report.syntheticResources,
            baselineEligible: isBaselineEligible,
            scenario: scenario
        )
    }
}
