import Testing
import Foundation
@testable import ViewLensKit

@Suite("GeneratedRegionMerger Tests (MCP-17.12)")
struct GeneratedRegionMergerTests {

    @Test("First-time generation appends the wrapped region")
    func testFirstTimeGenerationAppendsRegion() throws {
        let merged = try GeneratedRegionMerger.merge(
            regionID: NonvisualID("FixtureFlowForm:regression:0001"),
            newContent: "let x = 1",
            into: nil
        )
        #expect(merged.contains("// viewlens:generated:begin FixtureFlowForm:regression:0001"))
        #expect(merged.contains("// viewlens:generated:end FixtureFlowForm:regression:0001"))
        #expect(merged.contains("let x = 1"))
    }

    @Test("Regeneration replaces only the marked region, preserving hand-written code")
    func testRegenerationReplacesOnlyMarkedRegion() throws {
        let regionID = NonvisualID("FixtureFlowForm:regression:0001")
        let existing = """
        import Testing

        // hand-written helper, must survive regeneration
        func helper() -> Int { 42 }

        // viewlens:generated:begin \(regionID.rawValue)
        // AUTO-GENERATED by ViewLens
        let old = 1
        // viewlens:generated:end \(regionID.rawValue)

        // more hand-written code after the region
        func trailingHelper() -> Int { 7 }
        """

        let merged = try GeneratedRegionMerger.merge(regionID: regionID, newContent: "let new = 2", into: existing)

        #expect(merged.contains("func helper() -> Int { 42 }"))
        #expect(merged.contains("func trailingHelper() -> Int { 7 }"))
        #expect(merged.contains("let new = 2"))
        #expect(!merged.contains("let old = 1"))
    }

    @Test("Two independent regions coexist; merging one leaves the other untouched")
    func testTwoIndependentRegionsCoexist() throws {
        let regionA = NonvisualID("TemplateA:regression:0001")
        let regionB = NonvisualID("TemplateB:regression:0001")
        let existing = """
        // viewlens:generated:begin \(regionA.rawValue)
        let a = "original"
        // viewlens:generated:end \(regionA.rawValue)

        // viewlens:generated:begin \(regionB.rawValue)
        let b = "untouched"
        // viewlens:generated:end \(regionB.rawValue)
        """

        let merged = try GeneratedRegionMerger.merge(regionID: regionA, newContent: "let a = \"updated\"", into: existing)

        #expect(merged.contains("let a = \"updated\""))
        #expect(!merged.contains("let a = \"original\""))
        #expect(merged.contains("let b = \"untouched\""))
    }

    @Test("Missing end marker throws rather than overwriting")
    func testMissingEndMarkerThrows() {
        let regionID = NonvisualID("Broken:regression:0001")
        let existing = "// viewlens:generated:begin \(regionID.rawValue)\nlet x = 1\n"

        #expect(throws: MarkerParseError.missingEndMarker(id: regionID)) {
            try GeneratedRegionMerger.merge(regionID: regionID, newContent: "let y = 2", into: existing)
        }
    }

    @Test("Duplicate begin marker throws rather than overwriting")
    func testDuplicateBeginMarkerThrows() {
        let regionID = NonvisualID("Broken:regression:0002")
        let existing = """
        // viewlens:generated:begin \(regionID.rawValue)
        let x = 1
        // viewlens:generated:end \(regionID.rawValue)
        // viewlens:generated:begin \(regionID.rawValue)
        let y = 2
        // viewlens:generated:end \(regionID.rawValue)
        """

        #expect(throws: MarkerParseError.duplicateBeginMarker(id: regionID)) {
            try GeneratedRegionMerger.merge(regionID: regionID, newContent: "let z = 3", into: existing)
        }
    }

    @Test("Unmatched end marker throws rather than overwriting")
    func testUnmatchedEndMarkerThrows() {
        let regionID = NonvisualID("Broken:regression:0003")
        let existing = "let x = 1\n// viewlens:generated:end \(regionID.rawValue)\n"

        #expect(throws: MarkerParseError.unmatchedEndMarker(id: regionID)) {
            try GeneratedRegionMerger.merge(regionID: regionID, newContent: "let y = 2", into: existing)
        }
    }

    @Test("Malformed marker line throws rather than overwriting")
    func testMalformedMarkerLineThrows() {
        let regionID = NonvisualID("Broken:regression:0004")
        // Truncated marker: missing the trailing space + ID a bad hand-edit might leave behind.
        let existing = "// viewlens:generated:begin\nlet x = 1\n"

        #expect(throws: (any Error).self) {
            try GeneratedRegionMerger.merge(regionID: regionID, newContent: "let y = 2", into: existing)
        }
    }
}
