import Foundation
import ArgumentParser
import ViewLensKit

struct InstallHookCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "install-hook",
        abstract: "Installs a ViewLens Git Hook (pre-commit or pre-push) into the local repository."
    )

    @Option(name: .long, help: "Hook type to install: pre-commit or pre-push")
    var type: String = "pre-commit"

    func run() async throws {
        let repoRoot = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        let hooksDir = repoRoot.appendingPathComponent(".git").appendingPathComponent("hooks")

        guard FileManager.default.fileExists(atPath: repoRoot.appendingPathComponent(".git").path) else {
            fputs("❌ Error: Current directory is not a git repository root.\n", stderr)
            Darwin.exit(1)
        }

        try? FileManager.default.createDirectory(at: hooksDir, withIntermediateDirectories: true)

        let hookFile = hooksDir.appendingPathComponent(type)
        let hookScript = """
        #!/bin/sh
        # Auto-generated by ViewLens (https://github.com/SerialForBreakfast/ViewLens)
        echo "🛡️  Running ViewLens \(type) UI Quality Gate..."

        if command -v viewlens >/dev/null 2>&1; then
            viewlens hook \(type)
        elif [ -f "./.build/release/viewlens" ]; then
            ./.build/release/viewlens hook \(type)
        else
            echo "⚠️  ViewLens binary not found in PATH or .build/release. Run 'swift build -c release' first."
            exit 1
        fi
        """

        try hookScript.write(to: hookFile, atomically: true, encoding: .utf8)

        // Make executable (chmod +x)
        let chmodProcess = Process()
        chmodProcess.executableURL = URL(fileURLWithPath: "/bin/chmod")
        chmodProcess.arguments = ["+x", hookFile.path]
        try? chmodProcess.run()
        chmodProcess.waitUntilExit()

        print("✅ Successfully installed ViewLens \(type) git hook to: \(hookFile.path)")
        print("💡 Commits will now automatically run fast pre-commit HIG audits before being accepted.")
    }
}
